/* Generated By:JJTree: Do not edit this line. ASTAtribuicao.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package source;

public
class ASTAtribuicao extends SimpleNode {
  public ASTAtribuicao(int id) {
    super(id);
  }

  public ASTAtribuicao(DungeonCompilador p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DungeonCompiladorVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9615ec542b5f081479b51b06fc6390b1 (do not edit this line) */
