/* Generated By:JJTree: Do not edit this line. ASTBoolLiteral.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package source;

public
class ASTBoolLiteral extends SimpleNode {
  public ASTBoolLiteral(int id) {
    super(id);
  }

  public ASTBoolLiteral(DungeonCompilador p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DungeonCompiladorVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ba106181fe16091ed3683c99b41e78cf (do not edit this line) */
