/* Generated By:JJTree: Do not edit this line. ASTCondicional.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package source;

public
class ASTCondicional extends SimpleNode {
  public ASTCondicional(int id) {
    super(id);
  }

  public ASTCondicional(DungeonCompilador p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DungeonCompiladorVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=be7465600347c206360e59e214c03481 (do not edit this line) */
