/* Generated By:JJTree: Do not edit this line. ASTDeclaracao.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package source;

public
class ASTDeclaracao extends SimpleNode {
  public ASTDeclaracao(int id) {
    super(id);
  }

  public ASTDeclaracao(DungeonCompilador p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DungeonCompiladorVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1768865dbbb8cb2943ecb6892c7742cd (do not edit this line) */
