/* Generated By:JJTree: Do not edit this line. ASTFloatLiteral.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package source;

public
class ASTFloatLiteral extends SimpleNode {
  public ASTFloatLiteral(int id) {
    super(id);
  }

  public ASTFloatLiteral(DungeonCompilador p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DungeonCompiladorVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=dde4c9ad3ca2ea0796803faffccb757f (do not edit this line) */
