/* Generated By:JJTree: Do not edit this line. ASTIntLiteral.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package source;

public
class ASTIntLiteral extends SimpleNode {
  public ASTIntLiteral(int id) {
    super(id);
  }

  public ASTIntLiteral(DungeonCompilador p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DungeonCompiladorVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=40953f4bee355a0c54a20f478428bd18 (do not edit this line) */
