/* Generated By:JJTree: Do not edit this line. ASTId.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package source;

public
class ASTId extends SimpleNode {
  public ASTId(int id) {
    super(id);
  }

  public ASTId(DungeonCompilador p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DungeonCompiladorVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=59b07b9ca69b219d32adc793084be041 (do not edit this line) */
