/* Generated By:JJTree: Do not edit this line. ASTNot.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package source;

public
class ASTNot extends SimpleNode {
  public ASTNot(int id) {
    super(id);
  }

  public ASTNot(DungeonCompilador p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DungeonCompiladorVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=25885d4c324809093514e036dd03af82 (do not edit this line) */
