/* Generated By:JJTree: Do not edit this line. ASTRel.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package source;

public
class ASTRel extends SimpleNode {
  public ASTRel(int id) {
    super(id);
  }

  public ASTRel(DungeonCompilador p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DungeonCompiladorVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=2793d107ed231fed669a5a5d58e4f024 (do not edit this line) */
