/* Generated By:JavaCC: Do not edit this line. DungeonCompiladorVisitor.java Version 7.0.13 */
package source;

public interface DungeonCompiladorVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTPrograma node, Object data);
  public Object visit(ASTBloco node, Object data);
  public Object visit(ASTDeclaracao node, Object data);
  public Object visit(ASTTipo node, Object data);
  public Object visit(ASTAtribuicao node, Object data);
  public Object visit(ASTCondicional node, Object data);
  public Object visit(ASTWhile node, Object data);
  public Object visit(ASTDoUntil node, Object data);
  public Object visit(ASTOr node, Object data);
  public Object visit(ASTAnd node, Object data);
  public Object visit(ASTRel node, Object data);
  public Object visit(ASTAdd node, Object data);
  public Object visit(ASTMult node, Object data);
  public Object visit(ASTNot node, Object data);
  public Object visit(ASTId node, Object data);
  public Object visit(ASTIntLiteral node, Object data);
  public Object visit(ASTFloatLiteral node, Object data);
  public Object visit(ASTBoolLiteral node, Object data);
  public Object visit(ASTCharLiteral node, Object data);
}
/* JavaCC - OriginalChecksum=6e9df2a475d0f1236684017e6e176671 (do not edit this line) */
