/* Generated By:JavaCC: Do not edit this line. DungeonCompiladorConstants.java */
package source;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface DungeonCompiladorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INICIAPROG = 5;
  /** RegularExpression Id. */
  int ABREBLOCO = 6;
  /** RegularExpression Id. */
  int FECHABLOCO = 7;
  /** RegularExpression Id. */
  int FIMINSTRUCAO = 8;
  /** RegularExpression Id. */
  int TIPOINT = 9;
  /** RegularExpression Id. */
  int TIPOFLOAT = 10;
  /** RegularExpression Id. */
  int TIPOBOL = 11;
  /** RegularExpression Id. */
  int TIPOCHAR = 12;
  /** RegularExpression Id. */
  int IF = 13;
  /** RegularExpression Id. */
  int ABREPAR = 14;
  /** RegularExpression Id. */
  int FECHAPAR = 15;
  /** RegularExpression Id. */
  int OPREL = 16;
  /** RegularExpression Id. */
  int OPBOOL = 17;
  /** RegularExpression Id. */
  int ASSIGN = 18;
  /** RegularExpression Id. */
  int WHILE = 19;
  /** RegularExpression Id. */
  int DO = 20;
  /** RegularExpression Id. */
  int DOWHILE = 21;
  /** RegularExpression Id. */
  int OPAD = 22;
  /** RegularExpression Id. */
  int OPMULT = 23;
  /** RegularExpression Id. */
  int LETRA = 24;
  /** RegularExpression Id. */
  int DIGITO = 25;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 26;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"campanha\"",
    "\"mesa\"",
    "\"e_eh_aqui\"",
    "\"tpk\"",
    "\"forca\"",
    "\"destreza\"",
    "\"inteligencia\"",
    "\"sabedoria\"",
    "\"rola_um_dado_ai\"",
    "\"(\"",
    "\")\"",
    "<OPREL>",
    "<OPBOOL>",
    "\"=\"",
    "\"iniciativa\"",
    "\"sua_vez\"",
    "\"vez_do_monstro\"",
    "<OPAD>",
    "<OPMULT>",
    "<LETRA>",
    "<DIGITO>",
    "<IDENTIFICADOR>",
  };

}
