/* Generated By:JavaCC: Do not edit this line. DungeonCompiladorTreeConstants.java Version 7.0.13 */
package source;

public interface DungeonCompiladorTreeConstants
{
  public int JJTPROGRAMA = 0;
  public int JJTBLOCO = 1;
  public int JJTDECLARACAO = 2;
  public int JJTTIPO = 3;
  public int JJTVOID = 4;
  public int JJTATRIBUICAO = 5;
  public int JJTCONDICIONAL = 6;
  public int JJTWHILE = 7;
  public int JJTDOUNTIL = 8;
  public int JJTOR = 9;
  public int JJTAND = 10;
  public int JJTREL = 11;
  public int JJTADD = 12;
  public int JJTMULT = 13;
  public int JJTNOT = 14;
  public int JJTID = 15;
  public int JJTINTLITERAL = 16;
  public int JJTFLOATLITERAL = 17;
  public int JJTBOOLLITERAL = 18;
  public int JJTCHARLITERAL = 19;


  public String[] jjtNodeName = {
    "Programa",
    "Bloco",
    "Declaracao",
    "Tipo",
    "void",
    "Atribuicao",
    "Condicional",
    "While",
    "DoUntil",
    "Or",
    "And",
    "Rel",
    "Add",
    "Mult",
    "Not",
    "Id",
    "IntLiteral",
    "FloatLiteral",
    "BoolLiteral",
    "CharLiteral",
  };
}
/* JavaCC - OriginalChecksum=dd574a81fa5693549cba678bb9283614 (do not edit this line) */
