/* Generated By:JavaCC: Do not edit this line. DungeonCompiladorDefaultVisitor.java Version 7.0.13 */
package source;

public class DungeonCompiladorDefaultVisitor implements DungeonCompiladorVisitor{
  public Object defaultVisit(SimpleNode node, Object data){
    node.childrenAccept(this, data);
    return data;
  }
  public Object visit(SimpleNode node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTPrograma node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTBloco node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTDeclaracao node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTTipo node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTAtribuicao node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTCondicional node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTWhile node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTDoUntil node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTOr node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTAnd node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTRel node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTAdd node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTMult node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTNot node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTId node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTIntLiteral node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTFloatLiteral node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTBoolLiteral node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTCharLiteral node, Object data){
    return defaultVisit(node, data);
  }
}
/* JavaCC - OriginalChecksum=3900fc2dff7e7164696833bcca3cb1bb (do not edit this line) */
